export const COLORS = {
  saffron: '#FF9933',
  white: '#FFFFFF',
  green: '#138808',
  navy: '#000080',
};

export const CATEGORIES = [
  'Electronics', 
  'Fashion', 
  'Books & Stationery', 
  'Agriculture & Produce', 
  'Services', 
  'Home & Kitchen', 
  'Vehicles', 
  'Others'
];

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome',
    loginWithGoogle: 'Login with Google',
    logout: 'Logout',
    toggleLang: 'हिंदी',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    appName: 'BharatBarter',
    pureBarter: 'Pure Barter – No cash involved!',
    postNew: 'Post New Item',
    browse: 'Browse Items',
    home: 'Home',
    post: 'Post',
    profile: 'Profile',
    title: 'Title',
    description: 'Description',
    category: 'Category',
    estimatedValue: 'Estimated Value (₹)',
    city: 'City',
    pincode: 'Pincode (Optional)',
    submit: 'Submit Item',
    search: 'Search items...',
    filterCategory: 'All Categories',
    filterCity: 'All Cities',
    proposeTrade: 'Propose a Trade',
    owner: 'Owner',
    myItems: 'My Posted Items',
    noItems: 'No items found.',
    tradeMessage: 'Hi, I can offer my [item] in exchange...',
    sendProposal: 'Send Proposal',
    cancel: 'Cancel',
  },
  hi: {
    welcome: 'स्वागत है',
    loginWithGoogle: 'गूगल के साथ लॉगिन करें',
    logout: 'लॉगआउट',
    toggleLang: 'English',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    appName: 'भारतबार्टर',
    pureBarter: 'शुद्ध वस्तु विनिमय - कोई नकद शामिल नहीं!',
    postNew: 'नई वस्तु पोस्ट करें',
    browse: 'वस्तुएं देखें',
    home: 'होम',
    post: 'पोस्ट',
    profile: 'प्रोफ़ाइल',
    title: 'शीर्षक',
    description: 'विवरण',
    category: 'श्रेणी',
    estimatedValue: 'अनुमानित मूल्य (₹)',
    city: 'शहर',
    pincode: 'पिनकोड (वैकल्पिक)',
    submit: 'वस्तु सबमिट करें',
    search: 'वस्तुएं खोजें...',
    filterCategory: 'सभी श्रेणियां',
    filterCity: 'सभी शहर',
    proposeTrade: 'व्यापार का प्रस्ताव दें',
    owner: 'मालिक',
    myItems: 'मेरी पोस्ट की गई वस्तुएं',
    noItems: 'कोई वस्तु नहीं मिली।',
    tradeMessage: 'नमस्ते, मैं बदले में अपना [आइटम] दे सकता हूँ...',
    sendProposal: 'प्रस्ताव भेजें',
    cancel: 'रद्द करें',
  },
};
